name: product
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  get_it: ^7.7.0
  go_router: ^14.0.2
  riverpod: ^2.5.1


  cupertino_icons: ^1.0.6
  core_ui:
    path: ../../packages/core_ui
  core_libs:
    path: ../../packages/core_libs
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true
  # generate: true
